# This workflow will install Python dependencies, and runs tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build:
    
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macOs-latest']
        architecture: ['x64']

    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v2

    - name: build-windows
      if: matrix.os == 'windows-latest'
      run: |
        "%VS140COMNTOOLS%../../VC/vcvarsall.bat"
        build.bat

    - name: build-unix
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOs-latest'
      run: |
        make

    - name: run-unix
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOs-latest'
      run: |
        ./trec_eval

    - name: run-windows
      if: matrix.os == 'windows-latest'
      run: |
        trec_eval
    
    - name: test-unix
        make quicktest
        make longtest

    